import VersoBlog
open Verso Genre Blog

set_option pp.rawOnError true

-- The content of this page is generated by the template override for `/posts/`
-- in `Blog.Theme`; the list of posts grouped by year is rendered there.

#doc (Page) "Posts by Year" =>
