import VersoBlog
open Verso Genre Blog

set_option pp.rawOnError true

-- The content of this page is generated by the template override for `/tags/`
-- in `Blog.Theme`; the list of posts grouped by tag is rendered there. The
-- headline anchors match the ones from the old Jekyll site, so old links like
-- `/tags/#lean` continue to work.

#doc (Page) "Posts by Tag" =>
